version: "3.8"

services:
  articles-db:
    build: ./articles-db
    image: articles-db
    container_name: articles-db
    ports:
      - "9000:3306" 
    volumes:
      - articles-db-data:/var/lib/mysql
    networks:
      - articles-net

  articles-back:
    build: ./articles-back
    image: articles-back
    container_name: articles-back
    depends_on:
      - articles-db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://articles-db/articles_db
    networks:
      - articles-net

  articles-front:
    build: ./articles-front
    image: articles-front
    container_name: articles-front
    depends_on:
      - articles-back
    ports:
      - "3000:3000"
    networks:
      - articles-net

networks:
  articles-net:

volumes:
  articles-db-data:
